---
--- Generated by Jason long(https://github.com/londry/Encryption365_Lua)
--- Created by Jason long.
--- DateTime: 2021/9/27 2:14 下午
---
---
lua_package_path("/wwwroot/lib/resty/trustocean/encryption365/?.lua;;")
ngx.header.content_type = "text/html"
ngx.say("lua path: ", package.path)

--require("client")


ngx.say("sd")