---
--- Generated by Jason long(https://github.com/londry/Encryption365_Lua)
--- Created by Jason long.
--- DateTime: 2021/9/27 2:14 下午
---
local _M = {
    _VERSION = '1.0.0'
}

local http = require("resty.http")
local cjson = require("cjson")

local config = {
    -- TrustOcean Encryption365 SSL API
    api_endpoint = "https://encryption365.trustocean.com/",
    -- Account Email
    account_email = nil,
    -- Account Access Token
    account_token = nil,
    -- Account Webhook SignatureHash, This signature hash will be returned by API,
    -- and use to verify the webhook callback data in the future,
    -- It's a new feature will improved in the next version of Encryption365, may not
    -- fit with the previous client like Encryption365_Baota.
    account_webhook_signature_hash = nil,
}

local function create_http_client()
    local httpc = ngx.ctx.acme_httpc
    if not httpc then
        httpc = http.new()
        ngx.ctx.acme_httpc = httpc
    end
    return httpc
end

local function post(operation, payload)
    local http_client = create_http_client()
    local url = config.api_endpoint+operation
    local resp, err = http_client:request_uri(url,
            {
                method = "POST",
                body = payload,
                headers = {
                    ["content-type"] = "application/json",
                    ["user-agent"] = "ENC365-Lua/1.0 (https://github.com/londry/Encryption365_Lua)",
                }
            }
    )
    if err then
        return nil, nil, err
    end
    log(ngx_DEBUG, "enc365 request: ", url, " response: ", resp.body)
    local body = resp.body
    return body, err
end

function _M:test()
    return post("ping", [[]])
end

return _M